
["Weapon Speed Bonuses"]
	#Attack speed bonus for well-made quality weapons
	#Range: -2.0 ~ 2.0
	wellWeaponSpeed = 0.0
	#Attack speed bonus for perfect quality weapons
	#Range: -2.0 ~ 2.0
	perfectWeaponSpeed = 0.5
	#Attack speed penalty for poor quality weapons
	#Range: -2.0 ~ 2.0
	poorWeaponSpeed = -0.5
	#Attack speed bonus for expert quality weapons
	#Range: -2.0 ~ 2.0
	expertWeaponSpeed = 0.25

["Minigame Config"]
	#Default arrow speed for the forging minigame
	#Range: -5.0 ~ 5.0
	arrowSpeed = 2.0
	#Zone shrink factor for the forging minigame
	#Range: 0.0 ~ 1.0
	zoneShrinkFactor = 0.8
	#Default arrow speed increase for the forging minigame
	#Range: -5.0 ~ 5.0
	arrowSpeedIncrease = 0.5
	#Zone starting size for the forging minigame,  in percentage
	#Range: 0 ~ 100
	zoneStartingSize = 20
	#Maximum arrow speed for the forging minigame
	#Range: -10.0 ~ 10.0
	maxArrowSpeed = 5.0

["Balance Options"]
	#Whether or not obtaining fish with a Wooden Bucket should be enabled.
	fishObtainingEnabled = true
	#Whether or not milking entities with a Wooden Bucket should be enabled.
	milkingEnabled = true
	#Defines the maximum durability of a Wooden Bucket. (0 deactivates the durability)
	#Range: 0 ~ 10000
	durability = 0
	#Minimum temperature of fluid at which the Wooden Bucket breaks when emptied. (-1 means that bucket never breaks caused by high fluid temperature)
	#Range: 0 ~ 10000
	woodenBucketBreakTemperature = 1000

["Armor Bonuses"]
	#Armor bonus for expert quality armor
	#Range: -5.0 ~ 5.0
	expertArmorBonus = 1.0
	#Armor bonus for perfect quality armor
	#Range: -5.0 ~ 5.0
	perfectArmorBonus = 1.5
	#Armor penalty for poor quality armor
	#Range: -5.0 ~ 5.0
	poorArmorBonus = -1.0
	#Armor bonus for well-made quality armor
	#Range: -5.0 ~ 5.0
	wellArmorBonus = 0.0

["Weapon Damage Bonuses"]
	#Damage bonus for expert quality weapons
	#Range: -10.0 ~ 10.0
	expertWeaponDamage = 1.5
	#Damage bonus for well-made quality weapons
	#Range: -10.0 ~ 10.0
	wellWeaponDamage = 0.0
	#Damage penalty for poor quality weapons
	#Range: -10.0 ~ 10.0
	poorWeaponDamage = -1.0
	#Damage bonus for perfect quality weapons
	#Range: -10.0 ~ 10.0
	perfectWeaponDamage = 2.0

